repository:
    description: An interactive git visualization and tutorial. Aspiring students of git can use this app to educate and challenge themselves towards mastery of git!
    homepage: https://pcottle.github.io/learnGitBranching/
